apiVersion: v1
kind: Service
metadata:
  name: trend-service
spec:
  type: LoadBalancer
  selector:
    app: trend-app
  ports:
  - port: 80        # external port
    targetPort: 80  # matches containerPort
